#!/usr/bin/env bash
set -e

# Update source and POM with license headers
mvn -q license:update-file-header license:update-project-license

# Stage any files automatically modified by the above
git add pom.xml src/**/*.java

# Verify that license headers are present and valid
if ! mvn -q license:check-file-header; then
  echo "❌ Error: Problemas con las licencias - Verifica los archivos"
  exit 1
fi