#!/usr/bin/env bash
set -e
cd ether-parent
# Update source and POM with license headers
mvn -q license:update-file-header license:update-project-license

# Stage any files automatically modified by the above
git add LICENSE.txt pom.xml

# Verify that license headers are present and valid
if ! mvn -q license:check-file-header; then
  echo "❌ Error: Problemas con las licencias - Verifica los archivos"
  exit 1
fi